fix: add steps

diff --git a/.github/workflows/test_common.yml b/.github/workflows/test_common.yml
--- a/.github/workflows/test_common.yml
+++ b/.github/workflows/test_common.yml
@@ -20,12 +20,14 @@ jobs:
 
   install_docker:
     if: runner.os == 'macOS'
-    run: |
-      HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
-      sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
-      open -a /Applications/Docker.app --args --unattended --accept-license
-      echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
-      while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+    steps:
+      - name: Install Docker
+        run: |
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
   setup_docker:
     name: Set up Docker Buildx
